using System;
using System.IO;

namespace fMath.Diagnostics
{
    /// <summary>
    /// Fixed input corpus for cross-platform raw-hash determinism checks.
    ///
    /// Each record is eight raw int32 values generated by SplitMix64 from a fixed seed with a spread of
    /// magnitudes (1 raw .. full int32, gameplay-domain positions up to ±2048 m, angles over the whole
    /// turn). The generator is integer-only, so the corpus is identical on every platform; it is also
    /// committed as Tests/Determinism/fmath_v2_input_vectors.bin and tests assert both agree.
    /// Binary format: magic "FMC2", int32 record count, then count * 8 little-endian int32.
    /// </summary>
    public sealed class fMathDeterminismCorpus
    {
        public const ulong DefaultSeed = 0x2F4D415448563200UL; // "/MATHV2\0"
        public const int DefaultRecordCount = 4096;
        public const int ValuesPerRecord = 8;
        const uint MAGIC = 0x32434D46u; // "FMC2"

        readonly int[] _values;

        public int RecordCount { get; }

        fMathDeterminismCorpus(int[] values)
        {
            _values = values;
            RecordCount = values.Length / ValuesPerRecord;
        }

        public int Get(int record, int index) => _values[record * ValuesPerRecord + index];

        public static fMathDeterminismCorpus Generate(ulong seed = DefaultSeed, int recordCount = DefaultRecordCount)
        {
            var values = new int[recordCount * ValuesPerRecord];
            ulong state = seed;
            for (int i = 0; i < values.Length; i++)
            {
                ulong r = Next(ref state);
                int value = (int)(uint)r;
                switch (i % 4)
                {
                    case 0: break;                                                  // full int32 range
                    case 1: value >>= (int)((r >> 32) % 31); break;                 // spread of magnitudes (1 raw .. full)
                    case 2: value = (int)(((long)value * (2048L << 16)) >> 31); break; // gameplay domain ±2048 m
                    default: value >>= 8 + (int)((r >> 40) % 16); break;             // small and mid values
                }
                values[i] = value;
            }
            return new fMathDeterminismCorpus(values);
        }

        static ulong Next(ref ulong state)
        {
            ulong z = state += 0x9E3779B97F4A7C15UL;
            z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9UL;
            z = (z ^ (z >> 27)) * 0x94D049BB133111EBUL;
            return z ^ (z >> 31);
        }

        public void Write(Stream stream)
        {
            var buffer = new byte[4];
            WriteUInt(stream, buffer, MAGIC);
            WriteUInt(stream, buffer, (uint)RecordCount);
            for (int i = 0; i < _values.Length; i++)
                WriteUInt(stream, buffer, (uint)_values[i]);
        }

        public static fMathDeterminismCorpus Read(Stream stream)
        {
            var buffer = new byte[4];
            if (ReadUInt(stream, buffer) != MAGIC)
                throw new InvalidDataException("not an fMath v2 corpus");
            int count = (int)ReadUInt(stream, buffer);
            var values = new int[count * ValuesPerRecord];
            for (int i = 0; i < values.Length; i++)
                values[i] = (int)ReadUInt(stream, buffer);
            return new fMathDeterminismCorpus(values);
        }

        public bool ContentEquals(fMathDeterminismCorpus other)
        {
            if (other == null || other._values.Length != _values.Length)
                return false;
            for (int i = 0; i < _values.Length; i++)
                if (_values[i] != other._values[i])
                    return false;
            return true;
        }

        static void WriteUInt(Stream s, byte[] b, uint v)
        {
            b[0] = (byte)v; b[1] = (byte)(v >> 8); b[2] = (byte)(v >> 16); b[3] = (byte)(v >> 24);
            s.Write(b, 0, 4);
        }

        static uint ReadUInt(Stream s, byte[] b)
        {
            int read = 0;
            while (read < 4)
            {
                int n = s.Read(b, read, 4 - read);
                if (n <= 0) throw new EndOfStreamException();
                read += n;
            }
            return b[0] | (uint)b[1] << 8 | (uint)b[2] << 16 | (uint)b[3] << 24;
        }
    }
}
