using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace fMath.Tools
{
    /// <summary>
    /// Offline precision report: compares fMath v2 against double-precision references (double is only
    /// used here, never in the runtime) and records max absolute / relative error, the worst input,
    /// monotonicity failures and saturation counts.
    /// </summary>
    static class PrecisionReport
    {
        sealed class Row
        {
            public string Function;
            public string Domain;
            public string Unit;
            public long Samples;
            public double MaxAbsError;
            public double MaxRelError;
            public string WorstInput = "";
            public long MonotonicityFailures;
            public long Saturations;

            public void Record(double error, double reference, string input)
            {
                Samples++;
                double abs = Math.Abs(error);
                if (abs > MaxAbsError)
                {
                    MaxAbsError = abs;
                    WorstInput = input;
                }
                if (Math.Abs(reference) > 1e-12)
                    MaxRelError = Math.Max(MaxRelError, abs / Math.Abs(reference));
            }
        }

        const double Q16 = 65536.0;
        const double Q30 = 1073741824.0;
        const double TurnToRad = 2 * Math.PI / 4294967296.0;

        public static void Write(string markdownPath, string csvPath)
        {
            var rows = new List<Row>();
            rows.Add(Sqrt());
            rows.Add(SinCos());
            rows.Add(Atan2());
            rows.AddRange(Normalize());
            rows.Add(QuaternionRotation());

            var md = new StringBuilder();
            md.Append("# fMath v2 precision report\n\n");
            md.Append("Generated by `dotnet run -c Release --project DotNet~/fMath.Tools -- precision-report`.\n");
            md.Append("References are evaluated in double precision offline; the runtime never uses floating point.\n\n");
            md.Append("| function | domain | error unit | samples | max abs error | max rel error | worst input | monotonicity failures | saturations |\n");
            md.Append("|---|---|---|---:|---:|---:|---|---:|---:|\n");
            var csv = new StringBuilder("function,domain,unit,samples,max_abs_error,max_rel_error,worst_input,monotonicity_failures,saturations\n");
            foreach (Row r in rows)
            {
                md.Append("| ").Append(r.Function).Append(" | ").Append(r.Domain).Append(" | ").Append(r.Unit).Append(" | ").Append(r.Samples)
                  .Append(" | ").Append(F(r.MaxAbsError)).Append(" | ").Append(F(r.MaxRelError)).Append(" | `").Append(r.WorstInput)
                  .Append("` | ").Append(r.MonotonicityFailures).Append(" | ").Append(r.Saturations).Append(" |\n");
                csv.Append(r.Function).Append(',').Append(r.Domain).Append(',').Append(r.Unit).Append(',').Append(r.Samples).Append(',')
                   .Append(F(r.MaxAbsError)).Append(',').Append(F(r.MaxRelError)).Append(",\"").Append(r.WorstInput).Append("\",")
                   .Append(r.MonotonicityFailures).Append(',').Append(r.Saturations).Append('\n');
            }
            md.Append("\nError units: `raw Q16` = 1/65536, `raw Q30` = 2^-30, `rad` = radians, `m` = metres (1 unit).\n");
            File.WriteAllText(markdownPath, md.ToString().Replace("\r\n", "\n"));
            File.WriteAllText(csvPath, csv.ToString().Replace("\r\n", "\n"));
        }

        static string F(double v) => v.ToString("G4", CultureInfo.InvariantCulture);

        static Row Sqrt()
        {
            var row = new Row { Function = "ffloat.Sqrt", Domain = "all non-negative raw (stride 97) + [0, 2^20]", Unit = "raw Q16" };
            int prev = 0;
            for (long raw = 0; raw <= int.MaxValue; raw += raw < (1 << 20) ? 1 : 97)
            {
                int s = ffloat.Sqrt(ffloat.FromRaw((int)raw)).RawValue;
                double reference = Math.Sqrt(raw * Q16);
                row.Record(s - reference, reference, "raw " + raw);
                if (s < prev) row.MonotonicityFailures++;
                if (s == int.MaxValue) row.Saturations++;
                prev = s;
            }
            return row;
        }

        static Row SinCos()
        {
            var row = new Row { Function = "fTrig.Sin / Cos", Domain = "full turn, stride 1021 raw", Unit = "raw Q30" };
            int prev = int.MinValue;
            for (long raw = 0; raw <= uint.MaxValue; raw += 1021)
            {
                fAngle a = fAngle.FromRaw((uint)raw);
                int s = fTrig.Sin(a).RawValue, c = fTrig.Cos(a).RawValue;
                double rs = Math.Sin(raw * TurnToRad) * Q30, rc = Math.Cos(raw * TurnToRad) * Q30;
                row.Record(s - rs, rs, "angle raw " + raw + " (sin)");
                row.Record(c - rc, rc, "angle raw " + raw + " (cos)");
                if (raw <= 0x40000000L)
                {
                    if (s < prev) row.MonotonicityFailures++;
                    prev = s;
                }
            }
            return row;
        }

        static Row Atan2()
        {
            var row = new Row { Function = "fTrig.Atan2", Domain = "random y, x (1 raw .. full int32) + circle walk", Unit = "rad" };
            ulong state = 99;
            for (int i = 0; i < 2000000; i++)
            {
                int y = (int)Next(ref state) >> (int)(Next(ref state) % 31);
                int x = (int)Next(ref state) >> (int)(Next(ref state) % 31);
                if (x == 0 && y == 0) continue;
                uint got = fTrig.Atan2(ffloat.FromRaw(y), ffloat.FromRaw(x)).RawValue;
                double reference = Math.Atan2(y, x);
                double diff = got * TurnToRad - reference;
                diff -= Math.Round(diff / (2 * Math.PI)) * 2 * Math.PI;
                row.Record(diff, reference, "y " + y + ", x " + x);
            }
            uint prev = 0;
            for (int i = 1; i < 1 << 20; i++)
            {
                fAngle t = fAngle.FromRaw((uint)i << 12);
                long cx = (long)fTrig.Cos(t).RawValue * 1000, cy = (long)fTrig.Sin(t).RawValue * 1000;
                uint a = fTrig.Atan2Wide(cy, cx).RawValue;
                if (a < prev) row.MonotonicityFailures++;
                prev = a;
            }
            return row;
        }

        static IEnumerable<Row> Normalize()
        {
            var small = new Row { Function = "fVector3.TryNormalize", Domain = "components 1 raw .. 1 cm", Unit = "raw Q30" };
            var gameplay = new Row { Function = "fVector3.TryNormalize", Domain = "±2048 m", Unit = "raw Q30" };
            var full = new Row { Function = "fVector3.TryNormalize", Domain = "full int32 raw", Unit = "raw Q30" };
            ulong state = 7;
            for (int i = 0; i < 1000000; i++)
            {
                Sample(small, Range(ref state, 655));
                Sample(gameplay, Range(ref state, 2048 << 16));
                Sample(full, int.MaxValue);
            }
            return new[] { small, gameplay, full };

            void Sample(Row row, int limit)
            {
                int x = (int)(Next(ref state) % (ulong)(2L * limit + 1)) - limit;
                int y = (int)(Next(ref state) % (ulong)(2L * limit + 1)) - limit;
                int z = (int)(Next(ref state) % (ulong)(2L * limit + 1)) - limit;
                if (!fVector3.TryNormalize(fVector3.FromRaw(x, y, z), out fUnitVector3 u)) return;
                double len = Math.Sqrt((double)x * x + (double)y * y + (double)z * z);
                row.Record(u.x.RawValue - x / len * Q30, x / len * Q30, x + ", " + y + ", " + z);
                row.Record(u.y.RawValue - y / len * Q30, y / len * Q30, x + ", " + y + ", " + z);
                row.Record(u.z.RawValue - z / len * Q30, z / len * Q30, x + ", " + y + ", " + z);
            }
        }

        static int Range(ref ulong state, int max) => 1 + (int)(Next(ref state) % (ulong)max);

        static Row QuaternionRotation()
        {
            var row = new Row { Function = "fQuaternion * fVector3", Domain = "random rotation, |v| <= 2048 m", Unit = "m" };
            ulong state = 3;
            for (int i = 0; i < 500000; i++)
            {
                fVector3 axisVector = fVector3.FromRaw((int)Next(ref state) >> 8, (int)Next(ref state) >> 8, (int)Next(ref state) >> 8);
                if (!fQuaternion.TryAngleAxis(fAngle.FromRaw((uint)Next(ref state)), axisVector, out fQuaternion q)) continue;
                int limit = 2048 << 16;
                fVector3 v = fVector3.FromRaw((int)(Next(ref state) % (ulong)(2L * limit)) - limit, (int)(Next(ref state) % (ulong)(2L * limit)) - limit, (int)(Next(ref state) % (ulong)(2L * limit)) - limit);
                fVector3 r = q * v;
                double qx = q.x.ToDouble(), qy = q.y.ToDouble(), qz = q.z.ToDouble(), qw = q.w.ToDouble();
                double vx = v.x.ToDouble(), vy = v.y.ToDouble(), vz = v.z.ToDouble();
                double n = Math.Sqrt(qx * qx + qy * qy + qz * qz + qw * qw);
                qx /= n; qy /= n; qz /= n; qw /= n;
                double cx = qy * vz - qz * vy, cy = qz * vx - qx * vz, cz = qx * vy - qy * vx;
                double ex = vx + 2 * (qw * cx + qy * cz - qz * cy);
                double ey = vy + 2 * (qw * cy + qz * cx - qx * cz);
                double ez = vz + 2 * (qw * cz + qx * cy - qy * cx);
                double err = Math.Sqrt(Sq(r.x.ToDouble() - ex) + Sq(r.y.ToDouble() - ey) + Sq(r.z.ToDouble() - ez));
                row.Record(err, Math.Sqrt(vx * vx + vy * vy + vz * vz), v.ToString() + " by " + q);
            }
            return row;
        }

        static double Sq(double v) => v * v;

        static ulong Next(ref ulong state)
        {
            ulong z = state += 0x9E3779B97F4A7C15UL;
            z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9UL;
            z = (z ^ (z >> 27)) * 0x94D049BB133111EBUL;
            return z ^ (z >> 31);
        }
    }
}
